// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for \$defaultTargetPlatform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIsFCs3WrNC7AV3OKBZh8gsV8-pVV6y3g',
    appId: '1:8810329409:web:b6a5e61e28d6107aac9dc0',
    messagingSenderId: '8810329409',
    projectId: 'carehub-a5e11',
    authDomain: 'carehub-a5e11.firebaseapp.com',
    storageBucket: 'carehub-a5e11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLOSuPgVL-oxN4XPssLhh_ecPBq_Bl7mQ',
    appId: '1:8810329409:android:9b8d7de3dd90b67eac9dc0',
    messagingSenderId: '8810329409',
    projectId: 'carehub-a5e11',
    storageBucket: 'carehub-a5e11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8YUuyWE_WSksdpbbggMhIMWuU1KlEvNI',
    appId: '1:8810329409:ios:86faef25286b2e12ac9dc0',
    messagingSenderId: '8810329409',
    projectId: 'carehub-a5e11',
    storageBucket: 'carehub-a5e11.appspot.com',
    iosBundleId: 'com.breakingbarriers.careHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8YUuyWE_WSksdpbbggMhIMWuU1KlEvNI',
    appId: 'YOUR_MACOS_APP_ID', // Replace with your macos app ID
    messagingSenderId: '8810329409',
    projectId: 'carehub-a5e11',
    storageBucket: 'carehub-a5e11.appspot.com',
    iosBundleId: 'com.breakingbarriers.careHub',
  );
}
